# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Around the World in 287 Days 
email: nathanlubchenco@gmail.com 
description: > # this means to ignore newlines until "baseurl:"
  A feminist, atheist, vegetarian who struggles with depression and loves to play games attempts to
  vagabond around the world. 
  Boulder -> Japan -> Thailand -> Spain -> Portugal -> NYC -> Costa Rica -> Nicaragua -> Guatamala -> Mexico -> ?
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://novicevagabond.com" # the base hostname & protocol for your site
twitter_username: nathanlubchenco 
github_username:  nathanlubchenco 

# Build settings
markdown: kramdown
